repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(.*\.ipynb)$
      - id: trailing-whitespace
        exclude: ^(.*\.ipynb|AUDIT.*\.md)$
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src/.*\.py|lab/.+\.py|notebooks/.+\.py)$
      - id: ruff-format
        files: ^(src/.*\.py|lab/.+\.py|notebooks/.+\.py)$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        stages: [manual]
